// <auto-generated />
using System;
using FarmaLog.Nucleo.Infrastructure.Persistence;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace FarmaLog.Nucleo.Infrastructure.Persistence.Migrations
{
    [DbContext(typeof(NucleoDbContext))]
    [Migration("20260815124545_InicialNucleo")]
    partial class InicialNucleo
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "10.0.11")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("FarmaLog.Nucleo.Domain.Solicitudes.SolicitudDeIngresoPedido", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("CodigoLaboratorio")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)");

                    b.Property<string>("CuentaCliente")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<string>("DireccionDespacho")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<string>("DocumentoVentaCenabast")
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<bool>("EsCenabast")
                        .HasColumnType("bit");

                    b.Property<int>("Estado")
                        .HasColumnType("int");

                    b.Property<DateOnly>("FechaEntregaSolicitada")
                        .HasColumnType("date");

                    b.PrimitiveCollection<string>("MotivosDeRechazo")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("NumeroDelivery")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<string>("Observacion")
                        .HasMaxLength(300)
                        .HasColumnType("nvarchar(300)");

                    b.Property<string>("OrdenCompra")
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<string>("TipoOrdenVenta")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)");

                    b.Property<bool>("Urgencia")
                        .HasColumnType("bit");

                    b.HasKey("Id");

                    b.HasIndex("CodigoLaboratorio", "NumeroDelivery")
                        .IsUnique()
                        .HasDatabaseName("UX_Solicitudes_Laboratorio_Delivery");

                    b.ToTable("Solicitudes", (string)null);
                });

            modelBuilder.Entity("FarmaLog.Nucleo.Domain.Solicitudes.SolicitudDeIngresoPedido", b =>
                {
                    b.OwnsMany("FarmaLog.Nucleo.Domain.Solicitudes.LineaSolicitud", "Lineas", b1 =>
                        {
                            b1.Property<Guid>("SolicitudId")
                                .HasColumnType("uniqueidentifier");

                            b1.Property<int>("Id")
                                .ValueGeneratedOnAdd()
                                .HasColumnType("int");

                            SqlServerPropertyBuilderExtensions.UseIdentityColumn(b1.Property<int>("Id"));

                            b1.Property<int>("Cantidad")
                                .HasColumnType("int");

                            b1.Property<string>("EstadoInventario")
                                .IsRequired()
                                .HasMaxLength(50)
                                .HasColumnType("nvarchar(50)");

                            b1.Property<string>("Lote")
                                .HasMaxLength(50)
                                .HasColumnType("nvarchar(50)");

                            b1.Property<string>("Sku")
                                .IsRequired()
                                .HasMaxLength(50)
                                .HasColumnType("nvarchar(50)");

                            b1.HasKey("SolicitudId", "Id");

                            b1.ToTable("LineasDeSolicitud", (string)null);

                            b1.WithOwner()
                                .HasForeignKey("SolicitudId");
                        });

                    b.Navigation("Lineas");
                });
#pragma warning restore 612, 618
        }
    }
}
